server:
  port: 9000
spring:
  application:
    name: auth-server-oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=America/New_York
    username: root
    password: root
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka