server:
  port: 8765
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  prefix: /api
  routes:
    products:
      path: /products/**
      serviceId: products-service
      stripPrefix: false
    recipes:
      path: /recipes/**
      serviceId: recipes-service
      stripPrefix: false
  sensitive-headers:
security:
  oauth2:
    client:
      access-token-uri: http://localhost:9000/oauth/token
      user-authorization-uri: http://localhost:9000/oauth/authorize
      client-id: client
      client-secret: secret
    resource:
      userInfoUri: http://localhost:9000/user
logging:
  level:
    root: debug