GET http://localhost:8765/api/recipes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDg1NDIwOTksInVzZXJfbmFtZSI6InVzZXJuYW1lIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjgxMmRiMDYxLTJkNWEtNDlhNy1iODU3LWM3NDUwMzVjYmU2MiIsImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.5eOHrgUXP1MzDeNoj0vqsZWAkcmN7USCad-BYvKd7xE

###