GET http://localhost:8765/api/recipes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDg1NzE0NzUsInVzZXJfbmFtZSI6InVzZXJuYW1lIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjcyZmFlMjE2LTI2YmYtNDc5YS05NWRhLTAzYzZhYjk2MjJjYyIsImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdfQ.cGBbh2AFigHceEg3FDJfPkRNdBlmqk00DNYRavmWA1Q

###